#!/usr/bin/env python3
"""Summarize notes/ and chats/ files changed today into a journal entry.

Usage:
    python3 daily_notes_summary.py [--date YYYY-MM-DD] [--notes-dir DIR]
                                    [--chats-dir DIR] [--output-dir DIR]
                                    [--model MODEL] [--base-url URL]
                                    [--prompt-only] [--dry-run] [--force]

For the target date (default: today, local time), finds every file under
notes/ (**/*.md, **/*.html) and chats/ (*.md) whose modification time
falls on that date, then writes notes/journal/<date>.md containing:

  - A short overview in Simplified Chinese, generated by an
    OpenAI-compatible chat model from the changed files' titles and
    content excerpts.
  - A deterministic listing of every changed file, grouped by source
    tree, with title, relative path, modification time, and size.

OPENAI_API_KEY is read from the environment, falling back to ~/.env
(a LaunchAgent does not source shell rc files). Use --prompt-only to
write the LLM prompt instead of calling the API (no key needed). If no
files changed on the target date, nothing is written unless --force is
given.
"""

from __future__ import annotations

import argparse
import html
import json
import os
import re
import sys
import urllib.error
import urllib.request
from dataclasses import dataclass
from datetime import date, datetime
from pathlib import Path

_ICLOUD_KB = (
    Path.home()
    / "Library/Mobile Documents/com~apple~CloudDocs/workspace/knowledge"
)
DEFAULT_NOTES = _ICLOUD_KB / "notes"
DEFAULT_CHATS = _ICLOUD_KB / "chats"
DEFAULT_JOURNAL_DIR = DEFAULT_NOTES / "journal"

DEFAULT_MODEL = "gpt-5.5"
DEFAULT_BASE_URL = "https://api.openai.com/v1"

_TITLE_RE = re.compile(r"^#{1,6}\s+(.+?)\s*$", re.M)
_HTML_TITLE_RE = re.compile(r"<title>(.*?)</title>", re.IGNORECASE | re.DOTALL)
_FRONT_MATTER_RE = re.compile(r"\A---\s*\n.*?\n---\s*\n", re.DOTALL)
_TAG_RE = re.compile(r"<[^>]+>")
_WHITESPACE_RE = re.compile(r"\s+")

EXCERPT_CHARS = 600
MAX_FILES_FOR_LLM = 60


@dataclass
class ChangedFile:
    source: str  # "notes" or "chats"
    rel_path: Path  # relative to notes_dir or chats_dir
    title: str
    mtime: datetime
    size: int
    excerpt: str


def _mtime_date(path: Path) -> date:
    return datetime.fromtimestamp(path.stat().st_mtime).date()


def extract_title(path: Path, text: str) -> str:
    if path.suffix == ".html":
        m = _HTML_TITLE_RE.search(text)
        if m:
            return _WHITESPACE_RE.sub(" ", html.unescape(m.group(1))).strip()
    else:
        body = _FRONT_MATTER_RE.sub("", text, count=1)
        m = _TITLE_RE.search(body)
        if m:
            return m.group(1).strip()
    return path.stem


def extract_excerpt(path: Path, text: str) -> str:
    body = _FRONT_MATTER_RE.sub("", text, count=1)
    if path.suffix == ".html":
        body = html.unescape(_TAG_RE.sub(" ", body))
    else:
        body = _TITLE_RE.sub("", body, count=1)
    return _WHITESPACE_RE.sub(" ", body).strip()[:EXCERPT_CHARS]


def find_changed_files(
    root: Path, source: str, pattern: str, target: date, exclude: Path | None = None
) -> list[ChangedFile]:
    if not root.is_dir():
        return []
    out = []
    for path in sorted(root.glob(pattern)):
        if not path.is_file():
            continue
        if any(part.startswith(".") for part in path.relative_to(root).parts):
            continue
        if exclude is not None and path.is_relative_to(exclude):
            continue
        if _mtime_date(path) != target:
            continue
        try:
            text = path.read_text(encoding="utf-8", errors="replace")
        except OSError:
            continue
        out.append(
            ChangedFile(
                source=source,
                rel_path=path.relative_to(root),
                title=extract_title(path, text),
                mtime=datetime.fromtimestamp(path.stat().st_mtime),
                size=path.stat().st_size,
                excerpt=extract_excerpt(path, text),
            )
        )
    return out


def format_size(num_bytes: int) -> str:
    if num_bytes < 1024:
        return f"{num_bytes} B"
    return f"{num_bytes / 1024:.1f} KB"


def build_structured_section(
    notes_changed: list[ChangedFile], chats_changed: list[ChangedFile]
) -> str:
    lines = ["## 变更文件清单"]
    for label, items in (("notes/", notes_changed), ("chats/", chats_changed)):
        lines.append(f"\n### {label}（{len(items)}）")
        if not items:
            lines.append("\n- (无变更)")
            continue
        for cf in items:
            lines.append(
                f"\n- **{cf.title}** — `{cf.rel_path}`"
                f"（{cf.mtime.strftime('%H:%M')}，{format_size(cf.size)}）"
            )
    return "\n".join(lines) + "\n"


def build_llm_prompt(
    target: date, notes_changed: list[ChangedFile], chats_changed: list[ChangedFile]
) -> str:
    lines = [
        f"以下是 {target.isoformat()} 这一天，个人知识库中新增或修改的笔记/对话文件的"
        "标题与内容摘录。",
        "请用简体中文写一段不超过200字的总结，概括今天笔记/对话涉及的主要主题和值得关注"
        "的内容，可以适当分组，不要逐条列出文件名。",
        "",
    ]
    all_items = notes_changed + chats_changed
    for cf in all_items[:MAX_FILES_FOR_LLM]:
        lines.append(f"### [{cf.source}] {cf.title} ({cf.rel_path})")
        lines.append(cf.excerpt or "(无文本内容)")
        lines.append("")
    if len(all_items) > MAX_FILES_FOR_LLM:
        lines.append(f"...以及另外 {len(all_items) - MAX_FILES_FOR_LLM} 个文件（未展示）。")
    return "\n".join(lines)


def call_chat_completion(prompt: str, model: str, base_url: str, api_key: str) -> str:
    endpoint = base_url.rstrip("/") + "/chat/completions"
    payload = {
        "model": model,
        "messages": [
            {
                "role": "system",
                "content": "你是一个帮用户整理个人知识库每日变更的助手，输出简洁的中文总结。",
            },
            {"role": "user", "content": prompt},
        ],
    }

    request = urllib.request.Request(
        endpoint,
        data=json.dumps(payload).encode("utf-8"),
        headers={
            "Authorization": f"Bearer {api_key}",
            "Content-Type": "application/json",
        },
        method="POST",
    )

    try:
        with urllib.request.urlopen(request, timeout=180) as response:
            data = json.loads(response.read().decode("utf-8"))
    except urllib.error.HTTPError as exc:
        detail = exc.read().decode("utf-8", errors="replace")
        raise RuntimeError(f"API request failed with HTTP {exc.code}: {detail}") from exc
    except urllib.error.URLError as exc:
        raise RuntimeError(f"API request failed: {exc}") from exc

    try:
        return data["choices"][0]["message"]["content"].strip()
    except (KeyError, IndexError, TypeError) as exc:
        raise RuntimeError(f"Unexpected API response shape: {data}") from exc


def load_api_key() -> str | None:
    """Read OPENAI_API_KEY from the environment, falling back to ~/.env.

    A LaunchAgent's environment does not include variables set in shell rc
    files, so the key is re-read from ~/.env when not already present.
    """
    key = os.environ.get("OPENAI_API_KEY")
    if key:
        return key
    env_path = Path.home() / ".env"
    if not env_path.is_file():
        return None
    for line in env_path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        name, _, value = line.partition("=")
        if name.strip() == "OPENAI_API_KEY":
            return value.strip().strip('"').strip("'") or None
    return None


def parse_args(argv: list[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--date", help="Target date as YYYY-MM-DD. Defaults to today (local time)."
    )
    parser.add_argument("--notes-dir", type=Path, default=DEFAULT_NOTES)
    parser.add_argument("--chats-dir", type=Path, default=DEFAULT_CHATS)
    parser.add_argument("--output-dir", type=Path, default=DEFAULT_JOURNAL_DIR)
    parser.add_argument(
        "--model",
        default=os.environ.get("OPENAI_MODEL", DEFAULT_MODEL),
        help=f"Chat model name. Defaults to OPENAI_MODEL or {DEFAULT_MODEL}.",
    )
    parser.add_argument(
        "--base-url",
        default=os.environ.get("OPENAI_BASE_URL", DEFAULT_BASE_URL),
        help=f"OpenAI-compatible base URL. Defaults to OPENAI_BASE_URL or {DEFAULT_BASE_URL}.",
    )
    parser.add_argument(
        "--prompt-only",
        action="store_true",
        help="Write the LLM prompt instead of calling the API.",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Print the journal entry instead of writing it.",
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="Write a journal entry even if nothing changed on the target date.",
    )
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv if argv is not None else sys.argv[1:])
    target = date.fromisoformat(args.date) if args.date else date.today()

    notes_changed = find_changed_files(
        args.notes_dir, "notes", "**/*.md", target, exclude=args.output_dir
    )
    notes_changed += find_changed_files(
        args.notes_dir, "notes", "**/*.html", target, exclude=args.output_dir
    )
    notes_changed.sort(key=lambda cf: cf.rel_path)
    chats_changed = find_changed_files(args.chats_dir, "chats", "*.md", target)
    chats_changed.sort(key=lambda cf: cf.rel_path)

    if not notes_changed and not chats_changed and not args.force:
        print(f"No notes/chats changed on {target.isoformat()}; nothing written.")
        return 0

    if not notes_changed and not chats_changed:
        overview = "今天没有新增或修改的笔记。"
    elif args.prompt_only:
        prompt = build_llm_prompt(target, notes_changed, chats_changed)
        overview = f"```\n{prompt}\n```"
    else:
        api_key = load_api_key()
        if not api_key:
            print(
                "OPENAI_API_KEY not set (checked env and ~/.env); skipping LLM overview.",
                file=sys.stderr,
            )
            overview = "_(未生成：未配置 OPENAI_API_KEY)_"
        else:
            prompt = build_llm_prompt(target, notes_changed, chats_changed)
            try:
                overview = call_chat_completion(prompt, args.model, args.base_url, api_key)
            except RuntimeError as exc:
                print(f"LLM call failed: {exc}", file=sys.stderr)
                overview = f"_(总结生成失败: {exc})_"

    structured = build_structured_section(notes_changed, chats_changed)

    content = (
        f"# 笔记变更总结 - {target.isoformat()}\n\n"
        f"## 概览\n\n{overview}\n\n"
        f"{structured}"
    )

    if args.dry_run:
        print(content)
        return 0

    args.output_dir.mkdir(parents=True, exist_ok=True)
    out_path = args.output_dir / f"{target.isoformat()}.md"
    out_path.write_text(content, encoding="utf-8")
    print(f"Wrote {out_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
